/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package main

import (
	jsoniter "github.com/json-iterator/go"
	"k8s.io/apimachinery/pkg/runtime/schema"
	dnsv1alpha1 "kubeform.dev/provider-civo-api/apis/dns/v1alpha1"
	firewallv1alpha1 "kubeform.dev/provider-civo-api/apis/firewall/v1alpha1"
	instancev1alpha1 "kubeform.dev/provider-civo-api/apis/instance/v1alpha1"
	kubernetesv1alpha1 "kubeform.dev/provider-civo-api/apis/kubernetes/v1alpha1"
	loadbalancerv1alpha1 "kubeform.dev/provider-civo-api/apis/loadbalancer/v1alpha1"
	networkv1alpha1 "kubeform.dev/provider-civo-api/apis/network/v1alpha1"
	snapshotv1alpha1 "kubeform.dev/provider-civo-api/apis/snapshot/v1alpha1"
	sshv1alpha1 "kubeform.dev/provider-civo-api/apis/ssh/v1alpha1"
	templatev1alpha1 "kubeform.dev/provider-civo-api/apis/template/v1alpha1"
	volumev1alpha1 "kubeform.dev/provider-civo-api/apis/volume/v1alpha1"
	"kubeform.dev/provider-civo-controller/controllers"
)

type Data struct {
	JsonIt       jsoniter.API
	ResourceType string
}

var (
	allJsonIt = map[schema.GroupVersionResource]Data{
		{
			Group:    "dns.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "domainnames",
		}: {
			JsonIt:       controllers.GetJSONItr(dnsv1alpha1.GetEncoder(), dnsv1alpha1.GetDecoder()),
			ResourceType: "civo_dns_domain_name",
		},
		{
			Group:    "dns.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "domainrecords",
		}: {
			JsonIt:       controllers.GetJSONItr(dnsv1alpha1.GetEncoder(), dnsv1alpha1.GetDecoder()),
			ResourceType: "civo_dns_domain_record",
		},
		{
			Group:    "firewall.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "firewalls",
		}: {
			JsonIt:       controllers.GetJSONItr(firewallv1alpha1.GetEncoder(), firewallv1alpha1.GetDecoder()),
			ResourceType: "civo_firewall",
		},
		{
			Group:    "firewall.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "rules",
		}: {
			JsonIt:       controllers.GetJSONItr(firewallv1alpha1.GetEncoder(), firewallv1alpha1.GetDecoder()),
			ResourceType: "civo_firewall_rule",
		},
		{
			Group:    "instance.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "instances",
		}: {
			JsonIt:       controllers.GetJSONItr(instancev1alpha1.GetEncoder(), instancev1alpha1.GetDecoder()),
			ResourceType: "civo_instance",
		},
		{
			Group:    "kubernetes.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "clusters",
		}: {
			JsonIt:       controllers.GetJSONItr(kubernetesv1alpha1.GetEncoder(), kubernetesv1alpha1.GetDecoder()),
			ResourceType: "civo_kubernetes_cluster",
		},
		{
			Group:    "kubernetes.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "nodepools",
		}: {
			JsonIt:       controllers.GetJSONItr(kubernetesv1alpha1.GetEncoder(), kubernetesv1alpha1.GetDecoder()),
			ResourceType: "civo_kubernetes_node_pool",
		},
		{
			Group:    "loadbalancer.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "loadbalancers",
		}: {
			JsonIt:       controllers.GetJSONItr(loadbalancerv1alpha1.GetEncoder(), loadbalancerv1alpha1.GetDecoder()),
			ResourceType: "civo_loadbalancer",
		},
		{
			Group:    "network.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "networks",
		}: {
			JsonIt:       controllers.GetJSONItr(networkv1alpha1.GetEncoder(), networkv1alpha1.GetDecoder()),
			ResourceType: "civo_network",
		},
		{
			Group:    "snapshot.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "snapshots",
		}: {
			JsonIt:       controllers.GetJSONItr(snapshotv1alpha1.GetEncoder(), snapshotv1alpha1.GetDecoder()),
			ResourceType: "civo_snapshot",
		},
		{
			Group:    "ssh.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "keys",
		}: {
			JsonIt:       controllers.GetJSONItr(sshv1alpha1.GetEncoder(), sshv1alpha1.GetDecoder()),
			ResourceType: "civo_ssh_key",
		},
		{
			Group:    "template.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "templates",
		}: {
			JsonIt:       controllers.GetJSONItr(templatev1alpha1.GetEncoder(), templatev1alpha1.GetDecoder()),
			ResourceType: "civo_template",
		},
		{
			Group:    "volume.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "volumes",
		}: {
			JsonIt:       controllers.GetJSONItr(volumev1alpha1.GetEncoder(), volumev1alpha1.GetDecoder()),
			ResourceType: "civo_volume",
		},
		{
			Group:    "volume.civo.kubeform.com",
			Version:  "v1alpha1",
			Resource: "attachments",
		}: {
			JsonIt:       controllers.GetJSONItr(volumev1alpha1.GetEncoder(), volumev1alpha1.GetDecoder()),
			ResourceType: "civo_volume_attachment",
		},
	}
)

func getJsonItAndResType(gvr schema.GroupVersionResource) Data {
	return allJsonIt[gvr]
}
